package_assets: on
package_path: assets
compress_assets: on
javascript_compressor: closure
gzip_assets: on

javascripts:
  clock:
    - public/jsc/lib/vendor/*.js
    - public/jsc/lib/*.js
    - public/jsc/clock.v2.js

  admin:
    - public/jsc/lib/vendor/*.js
    - public/jsc/application.js

stylesheets:
  clock:
    - public/css/clock.css

  admin:
    - public/css/application.css
