branches:
  only:
    - master
rvm:
  - 1.9.2
  - 1.9.3
  - rbx-19mode
  - ree
before_install:
  - gem update --system
script: bundle exec thin start -d
notifications:
  email:
    - ethan.turkeltaub@gmail.com
